src/App.js, src/Components/MainPage/MainPage.js, src/Components/SingleProject/SingleProject.js, src/index.css
Added Single Project and Main Page Components with basic styling.
=> Project component

src/App.js
=> added "exact" to default path

src/Components/MainPage/MainPage.js, src/Components/SideBar/SideBar.js
also changed class to className in sidebar
=> mainpage has projects in state

src/Components/AccountPanel/AccountPanel.js, src/Components/SideBar/SideBar.js, src/Components/TipBox/TipBox.js, src/index.css
Added AccountPanel and TipBox and their tweaked styles a bit.
=> AccountPanel and TipBox added

src/Components/MblNav/MblNav.js, src/index.css
Added AccountPanel and TipBox to MblNav and tweaked the styles. Will make a component of nav-menu next, to add to MblNav
=> Mbl nav changes

a-team-wireframes/css/styles.css, src/Components/AccountPanel/AccountPanel.js, src/Components/Filters/Filters.js, src/Components/MblNav/MblNav.js, src/Components/NavMenu/NavMenu.js, src/Components/SingleProject/SingleProject.js, src/Components/TopNav/TopNav.css, src/Components/TopNav/TopNav.js, src/index.css
Updated styles and added NavMenu component
=> Updated Filters, SideBar and MblNav styles

src/Components/SingleProject/SingleProject.js, src/Components/TopNav/TopNav.js, src/index.css
fixed contrast issue and updated logo style
=> fixed contrast issue and updated logo style

src/Components/Filters/Filters.js, src/Components/MainPage/MainPage.js, src/Components/SingleProject/SingleProject.js, src/index.css
Updated style of all forms in the app.
=> made changes to main page layout styling

package-lock.json, package.json, src/Components/MainPage/MainPage.js, src/Components/SingleProject/SingleProject.js, src/Components/TopNav/TopNav.js, src/index.css
Made changes to main page, updated logo, and over styles
=> added icons, updated logo and main page styles

src/Components/AccountPanel/AccountPanel.js, src/Components/Filters/Filters.js, src/index.css
Updated account panel categories and styles.
=> Account panel changes

src/Components/Bidder/Bidder.js, src/Components/Filters/Filters.js, src/Components/LoginForm/LoginForm.css, src/index.css, src/routes/Project/Project.js
Updated bidder form and main page filters
=> Updating bidding form styles and main page filters

src/App.js, src/Components/NewProjectForm/NewProjectForm.js, src/Components/ProjectsCommentsForm/ProjectsCommentsForm.js, src/index.css, src/routes/Project/Project.js
Created ProjectsCommentsForm component
=> Comments stuff

src/Components/ProjectComments/ProjectComments.js, src/index.css, src/routes/Project/Project.js
=> added to Project and styled Comment component

src/Components/ProjectComments/ProjectComments.js, src/Components/ProjectsCommentsForm/ProjectsCommentsForm.js, src/index.css, src/routes/Project/Project.js
Made updates to layout and styling of ProjectCommentForm, Comments, and Project components
=> Update projects layout

src/Components/LoginForm/LoginForm.js, src/index.css
=> added aria-labels to login form and adjusted styles

src/Components/RegistrationForm/RegistrationForm.js
This page is still showing a contrast error, however it gives the following explanation:
"We are not sure this is an issue, because:"
"Element's background color could not be determined due to a background gradient"
Color gradients are necessary to maintain the app's color scheme, so they will not be changed.
=> added aria labels

src/Components/AccountPanel/AccountPanel.js, src/Components/Filters/Filters.js, src/Components/NewProjectForm/NewProjectForm.js, src/Components/SideBar/SideBar.js, src/Components/SingleProject/SingleProject.js, src/index.css, src/routes/MainPage/MainPage.js, src/routes/Project/Project.js
updated Project padding-top
added aria labels to form elements
changed h4's to h3's to follow header hierarchy best practices
This page is still showing a contrast error, however it gives the following explanation:
"We are not sure this is an issue, because:"
"Element's background color could not be determined due to a background gradient"
Color gradients are necessary to maintain the app's color scheme, so they will not be changed.
=> Axe main page

src/Components/Footer/Footer.js, src/Components/Logo/Logo.js, src/index.css, src/routes/LandingPage/LandingPage.js, src/routes/Login/Login.js, src/routes/MainPage/MainPage.js, src/routes/Project/Project.js, src/routes/Registration/Registration.js
added Footer and Logo component
=> added Footer and Logo component

src/Components/Footer/Footer.js, src/Components/NavMenu/NavMenu.js, src/Components/NewProjectForm/NewProjectForm.js, src/Components/ProjectsCommentsForm/ProjectsCommentsForm.js, src/Components/SingleProject/SingleProject.js, src/index.css, src/routes/LandingPage/LandingPage.js
Updated styles/layout on landing page, Projects page, Footer and TopNav
=> Updated styles/layout on landing page, Projects page, Footer and TopNav

src/Components/SingleProject/SingleProject.js
=> updated bid closed tag style

src/Components/Filters/Filters.js, src/Components/Logo/Logo.js, src/Components/MblNav/MblNav.js, src/index.css
Added search icon to filter button
=> Filter update

src/Components/Logo/Logo.js, src/Components/MblNav/MblNav.js, src/Components/SingleProject/SingleProject.js, src/index.css
=> Nav menu update

src/Components/Footer/Footer.js, src/Components/SingleProject/SingleProject.js, src/index.css, src/routes/LandingPage/LandingPage.js
Updated comment styles, landing page screenshot, and single project page links.
=> Single project comments landing updates

src/Components/TopNav/TopNav.js, src/index.css
Removed inline styles, adjusted logo style in footer and nav
=> Footer nav logo updates

src/Components/LoginForm/LoginForm.js, src/Components/MblNav/MblNav.js, src/index.css
Added a demo btn to login form that will automatically log users in with demo1234 profile
=> Demo login btn

src/index.css
Set footer to fixed accross all widths for Login Page
=> Login page height fix

src/Components/Footer/Footer.js, src/Components/MblNav/MblNav.js, src/routes/LandingPage/LandingPage.js, src/routes/MainPage/MainPage.js
Also fixed a few other Chrome warnings.
=> fixed react state update issue for landing page

src/Components/Footer/Footer.js, src/Components/LoginForm/LoginForm.js, src/Components/MblNav/MblNav.js, src/Components/RegistrationForm/RegistrationForm.js, src/index.css
Global changes:
Footer layout, responsiveness
MblNav now has logo and has animated movement on hamburger clicks
Login/Registration Forms spacing updated
=> Global style layout fixes
